package br.com.procempa.openproject.integration.entity;
// default package
// Generated 02/05/2016 16:14:34 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WorkPackages generated by hbm2java
 */
@Entity
@Table(name = "work_packages")
public class WorkPackages implements java.io.Serializable {

	private Integer id;
	private int typeId;
	private int projectId;
	private String subject;
	private Date dueDate;
	private Integer categoryId;
	private int statusId;
	private Integer assignedToId;
	private Integer priorityId;
	private Integer fixedVersionId;
	private int authorId;
	private int lockVersion;
	private int doneRatio;
	private Float estimatedHours;
	private Date createdAt;
	private Date updatedAt;
	private Date startDate;
	private Integer parentId;
	private Integer responsibleId;
	private Integer rootId;
	private Integer lft;
	private Integer rgt;
	private Integer position;
	private Integer storyPoints;
	private Float remainingHours;
	private Integer costObjectId;

	public WorkPackages() {
	}

	public WorkPackages(int typeId, int projectId, String subject,
			int statusId, int authorId, int lockVersion, int doneRatio) {
		this.typeId = typeId;
		this.projectId = projectId;
		this.subject = subject;
		this.statusId = statusId;
		this.authorId = authorId;
		this.lockVersion = lockVersion;
		this.doneRatio = doneRatio;
	}

	public WorkPackages(int typeId, int projectId, String subject,
			String description, Date dueDate, Integer categoryId, int statusId,
			Integer assignedToId, Integer priorityId, Integer fixedVersionId,
			int authorId, int lockVersion, int doneRatio, Float estimatedHours,
			Date createdAt, Date updatedAt, Date startDate, Integer parentId,
			Integer responsibleId, Integer rootId, Integer lft, Integer rgt,
			Integer position, Integer storyPoints, Float remainingHours,
			Integer costObjectId) {
		this.typeId = typeId;
		this.projectId = projectId;
		this.subject = subject;
		this.dueDate = dueDate;
		this.categoryId = categoryId;
		this.statusId = statusId;
		this.assignedToId = assignedToId;
		this.priorityId = priorityId;
		this.fixedVersionId = fixedVersionId;
		this.authorId = authorId;
		this.lockVersion = lockVersion;
		this.doneRatio = doneRatio;
		this.estimatedHours = estimatedHours;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.startDate = startDate;
		this.parentId = parentId;
		this.responsibleId = responsibleId;
		this.rootId = rootId;
		this.lft = lft;
		this.rgt = rgt;
		this.position = position;
		this.storyPoints = storyPoints;
		this.remainingHours = remainingHours;
		this.costObjectId = costObjectId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "type_id", nullable = false)
	public int getTypeId() {
		return this.typeId;
	}

	public void setTypeId(int typeId) {
		this.typeId = typeId;
	}

	@Column(name = "project_id", nullable = false)
	public int getProjectId() {
		return this.projectId;
	}

	public void setProjectId(int projectId) {
		this.projectId = projectId;
	}

	@Column(name = "subject", nullable = false)
	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "due_date", length = 10)
	public Date getDueDate() {
		return this.dueDate;
	}

	public void setDueDate(Date dueDate) {
		this.dueDate = dueDate;
	}

	@Column(name = "category_id")
	public Integer getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "status_id", nullable = false)
	public int getStatusId() {
		return this.statusId;
	}

	public void setStatusId(int statusId) {
		this.statusId = statusId;
	}

	@Column(name = "assigned_to_id")
	public Integer getAssignedToId() {
		return this.assignedToId;
	}

	public void setAssignedToId(Integer assignedToId) {
		this.assignedToId = assignedToId;
	}

	@Column(name = "priority_id")
	public Integer getPriorityId() {
		return this.priorityId;
	}

	public void setPriorityId(Integer priorityId) {
		this.priorityId = priorityId;
	}

	@Column(name = "fixed_version_id")
	public Integer getFixedVersionId() {
		return this.fixedVersionId;
	}

	public void setFixedVersionId(Integer fixedVersionId) {
		this.fixedVersionId = fixedVersionId;
	}

	@Column(name = "author_id", nullable = false)
	public int getAuthorId() {
		return this.authorId;
	}

	public void setAuthorId(int authorId) {
		this.authorId = authorId;
	}

	@Column(name = "lock_version", nullable = false)
	public int getLockVersion() {
		return this.lockVersion;
	}

	public void setLockVersion(int lockVersion) {
		this.lockVersion = lockVersion;
	}

	@Column(name = "done_ratio", nullable = false)
	public int getDoneRatio() {
		return this.doneRatio;
	}

	public void setDoneRatio(int doneRatio) {
		this.doneRatio = doneRatio;
	}

	@Column(name = "estimated_hours", precision = 12, scale = 0)
	public Float getEstimatedHours() {
		return this.estimatedHours;
	}

	public void setEstimatedHours(Float estimatedHours) {
		this.estimatedHours = estimatedHours;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "start_date", length = 10)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Column(name = "parent_id")
	public Integer getParentId() {
		return this.parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	@Column(name = "responsible_id")
	public Integer getResponsibleId() {
		return this.responsibleId;
	}

	public void setResponsibleId(Integer responsibleId) {
		this.responsibleId = responsibleId;
	}

	@Column(name = "root_id")
	public Integer getRootId() {
		return this.rootId;
	}

	public void setRootId(Integer rootId) {
		this.rootId = rootId;
	}

	@Column(name = "lft")
	public Integer getLft() {
		return this.lft;
	}

	public void setLft(Integer lft) {
		this.lft = lft;
	}

	@Column(name = "rgt")
	public Integer getRgt() {
		return this.rgt;
	}

	public void setRgt(Integer rgt) {
		this.rgt = rgt;
	}

	@Column(name = "position")
	public Integer getPosition() {
		return this.position;
	}

	public void setPosition(Integer position) {
		this.position = position;
	}

	@Column(name = "story_points")
	public Integer getStoryPoints() {
		return this.storyPoints;
	}

	public void setStoryPoints(Integer storyPoints) {
		this.storyPoints = storyPoints;
	}

	@Column(name = "remaining_hours", precision = 12, scale = 0)
	public Float getRemainingHours() {
		return this.remainingHours;
	}

	public void setRemainingHours(Float remainingHours) {
		this.remainingHours = remainingHours;
	}

	@Column(name = "cost_object_id")
	public Integer getCostObjectId() {
		return this.costObjectId;
	}

	public void setCostObjectId(Integer costObjectId) {
		this.costObjectId = costObjectId;
	}

}
